package ua.kpi.fpm.pzks.vlasov.tinyUn2.ui.view.user.extra.contacts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditUserExtraContactsViewDesign extends VerticalLayout {
    protected Grid<ua.kpi.fpm.pzks.vlasov.tinyUn2.backend.data.entity.UserExtraContactsEntity> list;
    protected VerticalLayout tmp_form1;
    protected Button add;
    protected VerticalLayout form;
    protected TextField type;
    protected TextField contact;
    protected TextField visibility;
    protected Button update;
    protected Button cancel;
    protected Button delete;

    public EditUserExtraContactsViewDesign() {
        Design.read(this);
    }
}
