package ua.kpi.fpm.pzks.vlasov.tinyUn2.ui.view.university.faculrty;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FacultyListEditViewDesign extends VerticalLayout {
    protected Button backwardPage;
    protected TextField search;
    protected Button add;
    protected Grid<ua.kpi.fpm.pzks.vlasov.tinyUn2.backend.data.entity.FacultyEntity> list;
    protected VerticalLayout form;
    protected TextField name;
    protected Button edit;
    protected Button update;
    protected Button cancel;
    protected Button delete;

    public FacultyListEditViewDesign() {
        Design.read(this);
    }
}
