package ua.kpi.fpm.pzks.vlasov.tinyUn2.ui.view.admin.user;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import ua.kpi.fpm.pzks.vlasov.tinyUn2.ui.view.admin.RoleSelect;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminUserViewDesign extends VerticalLayout {
    protected TextField search;
    protected Button add;
    protected Grid<ua.kpi.fpm.pzks.vlasov.tinyUn2.backend.data.entity.UserEntity> list;
    protected VerticalLayout form;
    protected TextField login;
    protected TextField password;
    protected TextField firstName;
    protected TextField secondName;
    protected RoleSelect role;
    protected Button update;
    protected Button cancel;
    protected Button delete;
    protected Button editExtraContacts;

    public AdminUserViewDesign() {
        Design.read(this);
    }
}
